import React, { useState } from 'react';
import { X, Phone, MessageCircle, Loader2, CheckCircle } from 'lucide-react';
import { toast } from 'sonner';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { supabase } from '@/db/supabase';
import { createOrder } from '@/services/orders';
import { formatPrice, buildWhatsAppMessage } from '@/lib/utils';
import type { Product, OrderFormData } from '@/types/types';

interface OrderModalProps {
  product: Product;
  open: boolean;
  onClose: () => void;
}

const WHATSAPP_NUMBER = '242069999999';
const PHONE_NUMBER = '+242069999999';

const cities = [
  'Pointe-Noire', 'Brazzaville', 'Dolisie', 'Nkayi', 'Ouesso',
  'Impfondo', 'Sibiti', 'Madingou', 'Kinkala', 'Autre'
];

export default function OrderModal({ product, open, onClose }: OrderModalProps) {
  const [step, setStep] = useState<'form' | 'success'>('form');
  const [loading, setLoading] = useState(false);
  const [orderNumber, setOrderNumber] = useState('');
  const [form, setForm] = useState<OrderFormData>({
    customer_name: '',
    customer_phone: '',
    customer_city: '',
    delivery_address: '',
    quantity: 1,
    comment: '',
  });

  const price = product.promotional_price ?? product.price;
  const total = price * form.quantity;

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>) => {
    const { name, value } = e.target;
    setForm(f => ({ ...f, [name]: name === 'quantity' ? Math.max(1, parseInt(value) || 1) : value }));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!form.customer_name || !form.customer_phone || !form.customer_city || !form.delivery_address) {
      toast.error('Veuillez remplir tous les champs obligatoires');
      return;
    }
    setLoading(true);
    try {
      const order = await createOrder(product.id, product.name, price, form);
      // order_number may be auto-generated by DB trigger or null fallback
      setOrderNumber(order.order_number || `CMD-${Date.now().toString().slice(-6)}`);
      setStep('success');
      toast.success('Commande enregistrée avec succès !');

      // Fire-and-forget: notify supervisor via WhatsApp Edge Function
      try {
        await supabase.functions.invoke('notify-whatsapp-order', {
          body: { order: { ...order, product_id: product.id } },
        });
      } catch (_) {
        // Silent — notification failure must not block the order success flow
      }
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : String(err);
      console.error('Order error:', msg);
      // Even if DB insert fails, offer WhatsApp fallback
      toast.error('Erreur base de données — utilisez WhatsApp pour commander directement');
      // Still show WhatsApp button prominently
      handleWhatsApp();
    } finally {
      setLoading(false);
    }
  };

  const handleWhatsApp = () => {
    const msg = buildWhatsAppMessage(
      product.name, form.customer_name, form.customer_phone,
      form.customer_city, form.delivery_address, form.quantity, price, form.comment
    );
    window.open(`https://wa.me/${WHATSAPP_NUMBER}?text=${msg}`, '_blank');
  };

  const handleReset = () => {
    setStep('form');
    setForm({ customer_name: '', customer_phone: '', customer_city: '', delivery_address: '', quantity: 1, comment: '' });
    onClose();
  };

  return (
    <Dialog open={open} onOpenChange={handleReset}>
      <DialogContent className="fixed left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 w-[calc(100%-2rem)] max-w-lg neu-flat border-0 z-50 max-h-[90dvh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="text-primary text-lg font-bold">
            {step === 'form' ? 'Commander ce produit' : 'Commande confirmée!'}
          </DialogTitle>
        </DialogHeader>

        {step === 'form' ? (
          <form onSubmit={handleSubmit} className="space-y-4">
            {/* Product summary */}
            <div className="neu-pressed rounded-xl p-3 flex items-center gap-3">
              <div className="flex-1 min-w-0">
                <div className="font-semibold text-sm text-foreground truncate">{product.name}</div>
                <div className="text-xs text-muted-foreground">{product.brands?.name}</div>
              </div>
              <div className="text-accent font-bold shrink-0">{formatPrice(price)}</div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
              <div>
                <label className="text-xs font-medium text-muted-foreground mb-1 block">Nom complet *</label>
                <input name="customer_name" value={form.customer_name} onChange={handleChange}
                  placeholder="Votre nom" required className="neu-input text-sm" />
              </div>
              <div>
                <label className="text-xs font-medium text-muted-foreground mb-1 block">Téléphone *</label>
                <input name="customer_phone" value={form.customer_phone} onChange={handleChange}
                  placeholder="+242 06 xxx xx xx" required className="neu-input text-sm" />
              </div>
              <div>
                <label className="text-xs font-medium text-muted-foreground mb-1 block">Ville *</label>
                <select name="customer_city" value={form.customer_city} onChange={handleChange}
                  required className="neu-input text-sm">
                  <option value="">Choisir une ville</option>
                  {cities.map(c => <option key={c} value={c}>{c}</option>)}
                </select>
              </div>
              <div>
                <label className="text-xs font-medium text-muted-foreground mb-1 block">Quantité</label>
                <input name="quantity" type="number" min="1" max={product.stock || 99}
                  value={form.quantity} onChange={handleChange} className="neu-input text-sm" />
              </div>
            </div>

            <div>
              <label className="text-xs font-medium text-muted-foreground mb-1 block">Adresse de livraison *</label>
              <input name="delivery_address" value={form.delivery_address} onChange={handleChange}
                placeholder="Quartier, rue, point de repère..." required className="neu-input text-sm" />
            </div>

            <div>
              <label className="text-xs font-medium text-muted-foreground mb-1 block">Commentaire (optionnel)</label>
              <textarea name="comment" value={form.comment} onChange={handleChange}
                placeholder="Informations complémentaires..." rows={2}
                className="neu-input text-sm resize-none" />
            </div>

            {/* Total */}
            <div className="neu-pressed rounded-xl p-3 flex justify-between items-center">
              <span className="text-sm font-medium">Total ({form.quantity} article{form.quantity > 1 ? 's' : ''})</span>
              <span className="text-lg font-bold text-accent">{formatPrice(total)}</span>
            </div>

            <div className="flex gap-2">
              <button type="submit" disabled={loading}
                className="neu-btn-primary flex-1 flex items-center justify-center gap-2 text-sm">
                {loading ? <Loader2 className="w-4 h-4 animate-spin" /> : null}
                {loading ? 'Envoi...' : 'Confirmer la commande'}
              </button>
              <button type="button" onClick={handleWhatsApp}
                className="px-4 py-2.5 rounded-xl bg-green-500 text-white text-sm font-semibold hover:bg-green-600 transition-colors flex items-center gap-1.5">
                <MessageCircle className="w-4 h-4" /> WhatsApp
              </button>
            </div>
          </form>
        ) : (
          <div className="text-center py-4 space-y-4">
            <div className="w-16 h-16 bg-green-100 rounded-full flex items-center justify-center mx-auto">
              <CheckCircle className="w-8 h-8 text-green-600" />
            </div>
            <div>
              <div className="text-muted-foreground text-sm">Numéro de commande</div>
              <div className="text-2xl font-bold text-primary">{orderNumber}</div>
            </div>
            <p className="text-sm text-muted-foreground">
              Votre commande a été enregistrée. Notre équipe vous contactera bientôt au <strong>{form.customer_phone}</strong>.
            </p>
            <div className="flex gap-2">
              <button onClick={handleWhatsApp}
                className="flex-1 py-2.5 rounded-xl bg-green-500 text-white text-sm font-semibold hover:bg-green-600 transition-colors flex items-center justify-center gap-2">
                <MessageCircle className="w-4 h-4" /> Contacter via WhatsApp
              </button>
              <a href={`tel:${PHONE_NUMBER}`}
                className="flex-1 py-2.5 rounded-xl bg-primary text-white text-sm font-semibold flex items-center justify-center gap-2">
                <Phone className="w-4 h-4" /> Appeler
              </a>
            </div>
            <button onClick={handleReset} className="text-sm text-muted-foreground underline">Fermer</button>
          </div>
        )}
      </DialogContent>
    </Dialog>
  );
}
